# Generated by Django 4.2.5 on 2023-09-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artname', models.CharField(max_length=30)),
                ('Artistname', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('Images', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('user_status', models.CharField(max_length=30)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.login')),
            ],
        ),
    ]
